export interface MealSuggestion {
  name: string;
  emoji: string;
  kcal: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  prepTime: string;
  ingredients: string[];
}

export interface MealSlot {
  type: string;
  label: string;
  time: string;
  suggestions: MealSuggestion[];
}

// Training day meals (~2000 kcal, 154g protein, 200g carbs, 55g fat)
export const trainingDayMeals: MealSlot[] = [
  {
    type: "REVEIL",
    label: "Petit-déjeuner",
    time: "7h00",
    suggestions: [
      {
        name: "Porridge protéiné aux fruits rouges",
        emoji: "🥣",
        kcal: 350,
        proteinG: 30,
        carbsG: 45,
        fatG: 6,
        prepTime: "5 min",
        ingredients: ["60g flocons d'avoine", "30g whey vanille", "100g fruits rouges", "200ml lait écrémé"],
      },
      {
        name: "Tartines œufs brouillés",
        emoji: "🍳",
        kcal: 370,
        proteinG: 28,
        carbsG: 35,
        fatG: 12,
        prepTime: "10 min",
        ingredients: ["3 œufs entiers", "2 tranches pain complet", "Sel, poivre, ciboulette"],
      },
      {
        name: "Smoothie protéiné banane",
        emoji: "🍌",
        kcal: 340,
        proteinG: 32,
        carbsG: 42,
        fatG: 5,
        prepTime: "3 min",
        ingredients: ["1 banane", "30g whey chocolat", "200ml lait d'amande", "1 cs beurre de cacahuète"],
      },
      {
        name: "Yaourt grec granola",
        emoji: "🫐",
        kcal: 360,
        proteinG: 28,
        carbsG: 40,
        fatG: 8,
        prepTime: "2 min",
        ingredients: ["200g yaourt grec 0%", "40g granola", "Miel", "Myrtilles"],
      },
    ],
  },
  {
    type: "PRE_TRAINING",
    label: "Pré-training",
    time: "11h00",
    suggestions: [
      {
        name: "Wrap poulet-avocat",
        emoji: "🌯",
        kcal: 400,
        proteinG: 35,
        carbsG: 38,
        fatG: 12,
        prepTime: "10 min",
        ingredients: ["120g poulet grillé", "1 tortilla complète", "1/4 avocat", "Laitue, tomate"],
      },
      {
        name: "Riz thon concombre",
        emoji: "🍚",
        kcal: 380,
        proteinG: 34,
        carbsG: 42,
        fatG: 8,
        prepTime: "15 min",
        ingredients: ["80g riz basmati", "1 boîte thon naturel", "Concombre", "Sauce soja"],
      },
      {
        name: "Sandwich dinde complet",
        emoji: "🥪",
        kcal: 390,
        proteinG: 32,
        carbsG: 40,
        fatG: 10,
        prepTime: "5 min",
        ingredients: ["4 tranches dinde", "2 tranches pain complet", "Moutarde", "Salade, tomate"],
      },
      {
        name: "Bowl quinoa poulet",
        emoji: "🥗",
        kcal: 410,
        proteinG: 36,
        carbsG: 40,
        fatG: 10,
        prepTime: "15 min",
        ingredients: ["80g quinoa", "120g poulet", "Légumes grillés", "Vinaigrette légère"],
      },
    ],
  },
  {
    type: "POST_TRAINING",
    label: "Post-training",
    time: "14h00",
    suggestions: [
      {
        name: "Riz poulet brocoli",
        emoji: "🍗",
        kcal: 500,
        proteinG: 45,
        carbsG: 50,
        fatG: 10,
        prepTime: "20 min",
        ingredients: ["100g riz basmati", "150g blanc de poulet", "150g brocoli", "1 cc huile d'olive"],
      },
      {
        name: "Pâtes bœuf haché",
        emoji: "🍝",
        kcal: 520,
        proteinG: 42,
        carbsG: 52,
        fatG: 12,
        prepTime: "15 min",
        ingredients: ["100g pâtes complètes", "130g bœuf haché 5%", "Sauce tomate", "Oignon, ail"],
      },
      {
        name: "Patate douce saumon",
        emoji: "🐟",
        kcal: 480,
        proteinG: 38,
        carbsG: 48,
        fatG: 14,
        prepTime: "25 min",
        ingredients: ["200g patate douce", "130g pavé de saumon", "Haricots verts", "Citron"],
      },
      {
        name: "Buddha bowl poulet",
        emoji: "🥙",
        kcal: 490,
        proteinG: 40,
        carbsG: 50,
        fatG: 12,
        prepTime: "15 min",
        ingredients: ["80g riz", "130g poulet", "Edamame", "Avocat, carotte râpée"],
      },
    ],
  },
  {
    type: "DINER",
    label: "Dîner",
    time: "19h00",
    suggestions: [
      {
        name: "Saumon grillé patate douce",
        emoji: "🥘",
        kcal: 450,
        proteinG: 35,
        carbsG: 42,
        fatG: 15,
        prepTime: "25 min",
        ingredients: ["140g saumon", "180g patate douce", "Épinards sautés", "Huile d'olive"],
      },
      {
        name: "Poulet rôti légumes",
        emoji: "🍖",
        kcal: 430,
        proteinG: 38,
        carbsG: 35,
        fatG: 14,
        prepTime: "30 min",
        ingredients: ["150g cuisse de poulet", "Courgette, poivron", "Pommes de terre", "Herbes de Provence"],
      },
      {
        name: "Omelette champignons",
        emoji: "🍳",
        kcal: 420,
        proteinG: 34,
        carbsG: 30,
        fatG: 16,
        prepTime: "10 min",
        ingredients: ["4 œufs", "Champignons", "Fromage allégé", "Salade verte"],
      },
      {
        name: "Steak haché purée",
        emoji: "🥩",
        kcal: 460,
        proteinG: 36,
        carbsG: 38,
        fatG: 14,
        prepTime: "20 min",
        ingredients: ["150g steak haché 5%", "200g pommes de terre", "Lait écrémé", "Haricots verts"],
      },
    ],
  },
  {
    type: "SNACK_SOIR",
    label: "Snack soir",
    time: "21h00",
    suggestions: [
      {
        name: "Yaourt grec miel noix",
        emoji: "🍯",
        kcal: 300,
        proteinG: 25,
        carbsG: 25,
        fatG: 10,
        prepTime: "2 min",
        ingredients: ["200g yaourt grec 0%", "1 cs miel", "15g noix", "Cannelle"],
      },
      {
        name: "Fromage blanc fruits",
        emoji: "🍓",
        kcal: 280,
        proteinG: 28,
        carbsG: 22,
        fatG: 6,
        prepTime: "2 min",
        ingredients: ["250g fromage blanc 0%", "100g fraises", "1 cc miel"],
      },
      {
        name: "Shake caséine",
        emoji: "🥛",
        kcal: 290,
        proteinG: 30,
        carbsG: 20,
        fatG: 8,
        prepTime: "2 min",
        ingredients: ["30g caséine vanille", "200ml lait écrémé", "1 cs beurre de cacahuète"],
      },
      {
        name: "Cottage cheese amandes",
        emoji: "🧀",
        kcal: 310,
        proteinG: 26,
        carbsG: 18,
        fatG: 12,
        prepTime: "2 min",
        ingredients: ["200g cottage cheese", "20g amandes", "1 cc miel", "Cannelle"],
      },
    ],
  },
];

// Rest day meals (~1800 kcal, 154g protein, ~150g carbs, ~55g fat)
export const restDayMeals: MealSlot[] = [
  {
    type: "REVEIL",
    label: "Petit-déjeuner",
    time: "8h00",
    suggestions: [
      {
        name: "Omelette légumes",
        emoji: "🍳",
        kcal: 320,
        proteinG: 28,
        carbsG: 15,
        fatG: 16,
        prepTime: "10 min",
        ingredients: ["3 œufs", "Épinards", "Tomate", "Fromage allégé"],
      },
      {
        name: "Porridge protéiné light",
        emoji: "🥣",
        kcal: 310,
        proteinG: 28,
        carbsG: 32,
        fatG: 6,
        prepTime: "5 min",
        ingredients: ["50g flocons d'avoine", "30g whey", "Cannelle", "150ml lait écrémé"],
      },
      {
        name: "Pancakes protéinés",
        emoji: "🥞",
        kcal: 330,
        proteinG: 30,
        carbsG: 28,
        fatG: 10,
        prepTime: "15 min",
        ingredients: ["1 banane", "2 œufs", "30g whey", "Myrtilles"],
      },
      {
        name: "Tartine avocat saumon fumé",
        emoji: "🥑",
        kcal: 340,
        proteinG: 26,
        carbsG: 22,
        fatG: 16,
        prepTime: "5 min",
        ingredients: ["1 tranche pain complet", "1/4 avocat", "60g saumon fumé", "Citron"],
      },
    ],
  },
  {
    type: "PRE_TRAINING",
    label: "Déjeuner léger",
    time: "12h00",
    suggestions: [
      {
        name: "Salade poulet grillé",
        emoji: "🥗",
        kcal: 380,
        proteinG: 36,
        carbsG: 18,
        fatG: 16,
        prepTime: "10 min",
        ingredients: ["140g poulet grillé", "Salade mixte", "1/4 avocat", "Vinaigrette huile d'olive"],
      },
      {
        name: "Wrap thon crudités",
        emoji: "🌯",
        kcal: 360,
        proteinG: 32,
        carbsG: 30,
        fatG: 12,
        prepTime: "5 min",
        ingredients: ["1 boîte thon", "1 tortilla", "Carottes râpées", "Concombre"],
      },
      {
        name: "Soupe lentilles",
        emoji: "🥣",
        kcal: 370,
        proteinG: 28,
        carbsG: 35,
        fatG: 10,
        prepTime: "20 min",
        ingredients: ["100g lentilles corail", "Carottes", "Oignon", "Cumin, curcuma"],
      },
      {
        name: "Bowl saumon avocat",
        emoji: "🐟",
        kcal: 400,
        proteinG: 34,
        carbsG: 20,
        fatG: 18,
        prepTime: "10 min",
        ingredients: ["120g saumon cru", "1/4 avocat", "Edamame", "Sauce soja, gingembre"],
      },
    ],
  },
  {
    type: "POST_TRAINING",
    label: "Goûter",
    time: "16h00",
    suggestions: [
      {
        name: "Yaourt grec granola",
        emoji: "🫐",
        kcal: 280,
        proteinG: 24,
        carbsG: 28,
        fatG: 8,
        prepTime: "2 min",
        ingredients: ["200g yaourt grec 0%", "30g granola", "Fruits rouges"],
      },
      {
        name: "Pomme beurre de cacahuète",
        emoji: "🍎",
        kcal: 260,
        proteinG: 10,
        carbsG: 30,
        fatG: 14,
        prepTime: "2 min",
        ingredients: ["1 pomme", "2 cs beurre de cacahuète naturel"],
      },
      {
        name: "Shake protéiné",
        emoji: "🥛",
        kcal: 250,
        proteinG: 28,
        carbsG: 18,
        fatG: 6,
        prepTime: "2 min",
        ingredients: ["30g whey", "1 banane", "200ml eau"],
      },
      {
        name: "Cottage cheese fruits secs",
        emoji: "🧀",
        kcal: 270,
        proteinG: 22,
        carbsG: 24,
        fatG: 10,
        prepTime: "2 min",
        ingredients: ["200g cottage cheese", "Mix fruits secs", "Miel"],
      },
    ],
  },
  {
    type: "DINER",
    label: "Dîner",
    time: "19h00",
    suggestions: [
      {
        name: "Cabillaud légumes vapeur",
        emoji: "🐟",
        kcal: 380,
        proteinG: 38,
        carbsG: 22,
        fatG: 10,
        prepTime: "20 min",
        ingredients: ["160g cabillaud", "Brocoli", "Carottes vapeur", "Citron, aneth"],
      },
      {
        name: "Poulet salade César light",
        emoji: "🥗",
        kcal: 400,
        proteinG: 36,
        carbsG: 18,
        fatG: 16,
        prepTime: "15 min",
        ingredients: ["140g poulet grillé", "Romaine", "Parmesan allégé", "Sauce yaourt"],
      },
      {
        name: "Tofu sauté légumes",
        emoji: "🥘",
        kcal: 370,
        proteinG: 30,
        carbsG: 25,
        fatG: 14,
        prepTime: "15 min",
        ingredients: ["200g tofu ferme", "Poivrons, courgette", "Sauce soja", "Sésame"],
      },
      {
        name: "Steak grillé salade",
        emoji: "🥩",
        kcal: 420,
        proteinG: 40,
        carbsG: 12,
        fatG: 18,
        prepTime: "15 min",
        ingredients: ["150g bavette", "Salade roquette", "Tomates cerises", "Balsamique"],
      },
    ],
  },
  {
    type: "SNACK_SOIR",
    label: "Snack soir",
    time: "21h00",
    suggestions: [
      {
        name: "Fromage blanc 0% vanille",
        emoji: "🍦",
        kcal: 240,
        proteinG: 28,
        carbsG: 16,
        fatG: 2,
        prepTime: "2 min",
        ingredients: ["250g fromage blanc 0%", "Extrait de vanille", "1 cc miel"],
      },
      {
        name: "Infusion + amandes",
        emoji: "🍵",
        kcal: 200,
        proteinG: 8,
        carbsG: 8,
        fatG: 16,
        prepTime: "3 min",
        ingredients: ["Tisane camomille", "25g amandes nature"],
      },
      {
        name: "Caséine chocolat",
        emoji: "🍫",
        kcal: 230,
        proteinG: 28,
        carbsG: 12,
        fatG: 5,
        prepTime: "2 min",
        ingredients: ["30g caséine chocolat", "200ml lait écrémé"],
      },
      {
        name: "Œufs durs",
        emoji: "🥚",
        kcal: 220,
        proteinG: 18,
        carbsG: 2,
        fatG: 14,
        prepTime: "12 min",
        ingredients: ["3 œufs durs", "Sel, poivre", "Moutarde"],
      },
    ],
  },
];
